add multi loglevels and number of logs displayed
RegenJacob/egui_logger pull request #2
Opened 2023-01-15 10:36 UTC by liquidhelium

2023-01-15 13:31 UTC, RegenJacob commented
Thank you for the pull request! 
I will test this later

2023-01-17 14:54 UTC, RegenJacob requested changes
Nice work! just some small tweaks would be nice e.g. some comments are unnecessary in my opinion and moving the log level selectors inside a menu_button

2023-01-17 14:54 UTC, RegenJacob commented on src/lib.rs
> +        // Error, Warn and Info
```suggestion
```

2023-01-17 14:54 UTC, RegenJacob commented on src/lib.rs
> +        // a counter
```suggestion
```

2023-01-17 14:54 UTC, RegenJacob commented on src/lib.rs
> +            }
```suggestion
            ui.menu_button("Log Levels", |ui| {
              for level in LEVELS
              {
                  if ui.selectable_label( self.loglevels[level as usize - 1], level.as_str()).clicked()
                  {
                      self.loglevels[level as usize - 1] = !self.loglevels[level as usize - 1];
                  }
              }
            }
```

Please replace the label with a menu_button containing the selectable Levels

2023-01-18 06:19 UTC, liquidhelium commented
Thank you! I'll do this later.

2023-01-18 06:28 UTC, liquidhelium commented
Fine, everything is ok now

2023-01-18 06:40 UTC, merged